spring:
  application:
    name: api-poc
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1data/** 
        - id: service2
          uri: lb://service2
          predicates:
           - Path=/anotheroperation/** 
managemement:
 tracing:
  sampling:
    probability: 1	
server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/
